# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c3621a7729e15368dfdc8bf05fba3755468112689c67fa0f3af37b58da8420fd182d31596deb8edece3c7138b7e96e167e704c4842863f306d9352c2e6217e0

test:
  secret_key_base: ecd092990adcd9d082cd4210ba58a8b81e93a6d156f9d1f20ca4449ac7aaedf7775bf70cdaf409695af36989ae42f68a6f69436c63e2d12bade9f4e7daef78e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
